### ISSUE TITLE
Can't follow certain accounts

### ISSUE THREAD

**Issue by Jerroder** [pluja/Parasitter#102]
Hi,

When I try to search and follow [this account](https://nitter.net/matteocosta_CM), I end up on "Something went wrong... But it's not your fault!"

Other people with underscore in their @ work so it doesn't seem to be the problem though.

**Comment by FireMasterK** [comment]
Which instance did you try?
![image](https://user-images.githubusercontent.com/20838718/95701458-41cc3980-0c67-11eb-9862-261513083487.png)

**Comment by pluja** [comment]
Locally, I too can follow the account. Maybe it was a temporal problem, did you try it more than once?

**Comment by Jerroder** [comment]
I already tried a few weeks ago, it's on a self-hosted instance.

My bad, it works now that I have updated it. I didn't work before, even after previous updates.
