### ISSUE TITLE
Migrate to youtube-dlc

### ISSUE THREAD

**Issue by FireMasterK** [pluja/Parasitter#123]
If you aren't aware, youtube-dl was hit with a DMCA takedown request at https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md

youtube-dlc is a fork of youtube-dl which is updated a lot more frequently and has a lot of features that youtube-dl doesn't have (for example, geo-blocking bypassing)

Repo Links:
https://pypi.org/project/youtube-dlc/
https://github.com/blackjack4494/yt-dlc

**Comment by pluja** [comment]
We are not using Youtube-dl anymore since 8efae823020655171f44811cd05b971ff05ca177, we may be reimplementing it if I notice too much changes from Youtube interface so I don't need to maintain the 'data fetch API' which is a modified version of the one used by youtube-local.

**Comment by FireMasterK** [comment]
Don't we use youtube-dl to fetch streams currently? It might be a wise idea to use youtube-dl to have lesser concerns with YouTube related changes such as #120.

(NewPipe has dealt with 3 changes Invidious has 2 dealt with in the past 2 weeks)

**Comment by pluja** [comment]
No, we currently don't depend on Youtube-dl in any way. But as I said, maybe it would be wise to use it in order to avoid future problems with Youtube changes.

**Comment by FireMasterK** [comment]
That might be wise, I do see occasional errors(with no server-side logs) when Yotter tries to fetch the stream links.

**Comment by pluja** [comment]
I forgot to mention this issue on the commit message. But here's the implementation: 78d6044dd2ec9d944fc152781bb60cbef3c7c570

**Comment by pluja** [comment]
Will be testing and fixing the following days. Will close this issue when we think that it works all ok and it is fine to use as definitive.

**Comment by FireMasterK** [comment]
From what I can see, it works fine 👍

**Comment by pluja** [comment]
Maybe we can close this issue? Do we agree that it is working fine?

**Comment by FireMasterK** [comment]
Yep :)
