### ISSUE TITLE
PYPY based Docker images

### ISSUE THREAD

**Issue by FireMasterK** [pluja/Parasitter#125]
This is something I'm working on.

https://doc.pypy.org/en/latest/cpython_differences.html

**Comment by pluja** [comment]
Huh! That would be nice. Its is compatible with the actual code?

**Comment by FireMasterK** [comment]
Yes, I got an image working with everything working (twitter and youtube), the only thing that's left for me to do before committing is to fix an issue with llvmlite (the pip requirement), as it refuses to install with the outdated version on Debian buster, my current solution is to add it as a repository and get the required version.

**Comment by FireMasterK** [comment]
What does the [llvmlite](https://github.com/ytorg/Yotter/blob/dev-indep/requirements.txt#L31) requirement do? I built Yotter without it and it seemed to work just fine, is it a required dependency for something?

**Comment by pluja** [comment]
The requirements.txt needs to be cleaned up. I think that I have never really cleaned it up. I will do it today.

It was used on a previous version but it is now useless.

**Comment by pluja** [comment]
Done, the requirements.txt contains now only the necessary.

**Comment by FireMasterK** [comment]
What about https://github.com/ytorg/Yotter/commit/be30aa5c82f57804a0fd51264d5feda283c960ad#commitcomment-43727694?
Also, that commit reduced the image build time to just 30 minutes from 1 hour 45 minutes and reduced the image size to just 33MB 👍.

**Comment by pluja** [comment]
Fixed now!

**Comment by FireMasterK** [comment]
Added in d654ed132d980542e0e295258ee95150e0b9b7a3.
