### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by diazepan** [pluja/Parasitter#13]
I tried to use it and when I go to localhost:5000 I'm welcomed with a login page with an option to register

When I try to register it says "This is username is taken! Choose a different one." and when I try to login with that user it says invalid username or password

**Comment by pluja** [comment]
Yeah, I know! I'm working on it, in a few minutes it will be solved. It is because of the Database logic I set up on the very beginning of the project. You can always register using "test" username in the meanwhile.

Thank you!

**Comment by pluja** [comment]
Solved now! (Only on the [new version branch](https://github.com/pluja/Parasitter/tree/dev-indep))
