### ISSUE TITLE
[feature request] print version/commit-hash somewhere on the page

### ISSUE THREAD

**Issue by vladimiry** [pluja/Parasitter#130]
Somewhere in the info block I guess https://github.com/ytorg/Yotter/blob/d27990e56a66d51c81b5c188b02a70048a4f6c60/app/templates/settings.html#L87

**Comment by pluja** [comment]
This is a good idea. I was already asked for it via mail and I am planning to implement it soon :D

**Comment by FireMasterK** [comment]
How would we want to do this?

**Comment by vladimiry** [comment]
Just to be clear. I mean displaying the commit-hash of the deployed version instance of which user opens in a browser, not the most recent commit from github repository. So the value needs to be embedded into the code at some point (I guess there is no build process stage when it comes to Python).

**Comment by pluja** [comment]
Of course, as a versioning method so users can know if the instance is updated!

**Comment by FireMasterK** [comment]
I'm aware, but how? `.git/FETCH_HEAD` or `git rev-list HEAD --max-count=1 --abbrev-commit`?

**Comment by vladimiry** [comment]
Maybe `git rev-parse HEAD` or `git rev-parse --short HEAD` for short value.

**Comment by FireMasterK** [comment]
We'll have to think of a way of doing this in docker too, I really don't want to install git on an image. I'm considering writing the version to a file when building the image then reading from it or if it doesn't exist, fall back to a git command.

**Comment by pluja** [comment]
You can now see the Yotter version on the status page:
https://yotter.xyz/status

Older versions will not display the server version. Also, it will need to be manually changed for now until I can find an automatic solution for this.

**Comment by pluja** [comment]
b285081ca8ce6eee220896795ab1de1e98f53c2b and 4b098d7f521965fdbda8ca6f778aa2ed951cb8f4 automate it. Closing the issue.

**Comment by FireMasterK** [comment]
Won't this break on docker as git isn't installed?

**Comment by pluja** [comment]
Didn't thought about that. Reopening the issue

**Comment by pluja** [comment]
@FireMasterK we can close this issue if you confirm it works on Docker.

**Comment by FireMasterK** [comment]
Yep, I'll work on testing this tomorrow

**Comment by pluja** [comment]
Closing this as it has already been adressed.
