### ISSUE TITLE
[feature request] navigation using arrow keys + space

### ISSUE THREAD

**Issue by vladimiry** [pluja/Parasitter#144]
space: video toggling pause
arrows up/down: video volume level control
arrows left/right: video rewind (plus rewind step configuration in the settings)

**Comment by pluja** [comment]
This would be pretty good. I have to check on video.js options and do it!

**Comment by vladimiry** [comment]
By the way the readme says

>  But if JavaScript is disabled Yotter still works perfectly and uses the default HTML video player.

But it doesn't work for me with disabled JS (I disabled JS hoping that browser's built-in player will support keyboard navigation).

**Comment by FireMasterK** [comment]
@pluja I used https://github.com/ctd1500/videojs-hotkeys for my new project, it works perfectly.

**Comment by pluja** [comment]
Nice thank you!

**Comment by pluja** [comment]
Added support for this! :D

**Comment by vladimiry** [comment]
Can confirm it works. The only minor issue is that when the page gets just loaded the space key pressing doesn't start the video but scrolls the page down apparently because the `video` element is not focused on page load.

**Comment by pluja** [comment]
I'll take a look on that!
