### ISSUE TITLE
How were you able to move the time on videos?

### ISSUE THREAD

**Issue by mooseyoose** [pluja/Parasitter#152]
I'm trying to create a small video proxy myself and I can successfully stream the video. But I skip the video ahead in time, it gets stuck. This is my function thats working:

`@app.route('/stream', methods=['GET'])
def stream():
    url = "#"
    req = requests.get(url, stream = True)
    with requests.get(url, stream=True) as response:
        return Response(req.iter_content(chunk_size=100*1024), mimetype=req.headers['Content-Type'], content_type=req.headers['Content-Type'], direct_passthrough=True)`

Would love to know how you fixed that issue.

**Comment by FireMasterK** [comment]
Most instances would be using https://github.com/FireMasterK/http3-ytproxy, otherwise, they can use Nginx too, but that'll have issues with TTFB.
