### ISSUE TITLE
Support apache

### ISSUE THREAD

**Issue by arankaren** [pluja/Parasitter#155]
I have some servers that only work with apache. They would be so kind to share with me an example of how to configure yotter in apache

**Comment by quantumfx** [comment]
It's common for webserver to use nginx as the webserver and also act as a reverse proxy for apache, see e.g. [this tutorial](https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-as-a-web-server-and-reverse-proxy-for-apache-on-one-ubuntu-20-04-server).

**Comment by arankaren** [comment]
> It's common for webserver to use nginx as the webserver and also act as a reverse proxy for apache, see e.g. [this tutorial](https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-as-a-web-server-and-reverse-proxy-for-apache-on-one-ubuntu-20-04-server).

thank you!
