### ISSUE TITLE
After upgrading to 0.2.2 I am getting a load of 500 errors on videos

### ISSUE THREAD

**Issue by jankytech** [pluja/Parasitter#156]
**Describe the bug**
I am seeing many 500 errors when loading the video page. I think it might be the comment profile images but not entirely sure. 

**To Reproduce**
1. Go to any video page
2. View the js console

**Expected behavior**
No 500 errors on the video page

**Screenshots**
![image](https://user-images.githubusercontent.com/13768749/100083691-ab805b80-2e41-11eb-839e-3b3b173c855c.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: Firefox 
 - Version: 83.0

**Additional context**
I build the docker container from the dockerfile rather than using the latest docker hub repo.

**Comment by pluja** [comment]
@mansguiche  Ah.. I see. Can you confirm that the comments profile images are broken?

**Comment by jankytech** [comment]
Yes they seem to be broken.
![image](https://user-images.githubusercontent.com/13768749/100092813-965df980-2e4e-11eb-8a3a-c25bedcba3df.png)

**Comment by pluja** [comment]
Ok. This is related to the comments profile pictures. I'll be taking a look as soon as I can.

**Comment by FireMasterK** [comment]
If you're running my proxy and have a route for /ytc/ it in your reverse proxy, it should work.

**Comment by FireMasterK** [comment]
Support for it was added here: https://github.com/FireMasterK/http3-ytproxy/commit/a8981a44c7a535558c204348b032df3114cadcc3

**Comment by pluja** [comment]
@FireMasterK  How should I add support for http3-proxy without docker? I'll investigate later.

**Comment by FireMasterK** [comment]
Currently, the only way to run it by downloading go, and building it like so:
```
git clone https://github.com/FireMasterK/http3-ytproxy
cd http3-ytproxy
go build -ldflags "-s -w" main.go
mv main http3-ytproxy
```
You can then run it by using `./http3-ytproxy`.

**Comment by pluja** [comment]
@FireMasterK Should then I disable any nginx proxy config?

**Comment by FireMasterK** [comment]
Yes, all of them, this would replace them basically.

**Comment by pluja** [comment]
Nice

**Comment by pluja** [comment]
> You can then run it by using ./http3-ytproxy.

Is there a way to run it on the background?

**Comment by FireMasterK** [comment]
A `systemd` service would probably be the best solution, you can also `screen` session, which is what I use for development.

**Comment by pluja** [comment]
Testing this right now, just setted a systemd service but it is not proxying nothing. Just deleted:
```
location ~ (^videoplayback$|/videoplayback|/vi/|/a/|/api/|/ytc/) {
        proxy_buffering off;
        resolver 1.1.1.1 ipv6=off;
        proxy_pass https://$arg_host;
        proxy_set_header Host $arg_host;
        proxy_ssl_server_name on;
        add_header Access-Control-Allow-Origin *;
        sendfile on;
        tcp_nopush on;
        aio threads=default;
    }
```

from my nginx config. Maybe I'm doing something wrong.

**Comment by FireMasterK** [comment]
Did you add a location like this?:
```
location ~ (^/videoplayback$|/videoplayback/|/vi/|/a/|/ytc/) {
        proxy_pass http://unix:/var/run/ytproxy/http-proxy.sock;
        add_header Access-Control-Allow-Origin *;
        sendfile on;
        tcp_nopush on;
        aio_write on;
        aio threads=default;
        directio 512;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
```

**Comment by pluja** [comment]
@mansguiche As I think you may have the manual installation, I now added instructions on how to set up the `http3-ytproxy` on the Self-hosting guide. Check that out and ask if you need any help.

Closing this issue as using `http3-ytproxy` solves it.

**Comment by jankytech** [comment]
Thanks for you help, i will try that this week

**Comment by pluja** [comment]
Comment here if you need any help!

**Comment by jankytech** [comment]
I just tried @FireMasterK 's location configuration and that worked for me. I think i had a much older version without the /ytc/ in the regex.

Everything seems to be working now. Thanks for the help.

**Comment by pluja** [comment]
Nice!
