### ISSUE TITLE
Proxy images through the server 

### ISSUE THREAD

**Issue by Jerroder** [pluja/Parasitter#18]
Hi,

On the main page it's stated

> Important note: The client never connects to Google / Youtube however, the server does in order to gather all the necessary things!

However, I noticed that in the YouTube part of Yotter, my browser loads ytimg.com for thumbnails as well as ggpht.com and googleusercontent.com for channel images.

**Comment by SuperSandro2000** [comment]
I suggest to rewrite the image urls to an external image proxy which can optionally be locally hosted. This saves a lot of development and maintenance effort. Right now I can think of camo and images.weserv.nl.

**Comment by Jerroder** [comment]
I see, but then it's not doable on a phone :/

**Comment by SuperSandro2000** [comment]
This also works on your phone.

**Comment by pluja** [comment]
True! Working on it!!

**Comment by pluja** [comment]
It's done, although I still need to verify all images are passed through the proxy.

**Comment by Jerroder** [comment]
Seems to work, I'm not loading these domains anymore. Thanks!
