### ISSUE TITLE
Instance only load tweets from one user

### ISSUE THREAD

**Issue by Jerroder** [pluja/Parasitter#187]
**Describe the bug**
Two or three days ago, when I went to the twitter part of Yotter, I noticed I only had tweets from only one of my 50 followings in the timeline. Since I just updated Yotter from a multiple-months old instance, I decided to reinstall it entirely (deleting `.cache`, the `Yotter` folder and the database) and then `git clone` etc. It has been working fine for two (or three) days and tonight the problem is back. From refresh to refresh, the user in the timeline changes but it often goes back to the same one.

**To Reproduce**
I have no idea.

**Expected behavior**
See the correct timeline with all users.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 78.6.1esr

**Smartphone (please complete the following information):**
 - OS: iOS 14.2
 - Browser: Safari

**Additional context**
I haven't found any log file so it's hard to troubleshoot.

**Comment by Jerroder** [comment]
I haven't touch anything and it came back as it should: every followed users. I'll give an update should the issue appear again soon.

**Comment by pluja** [comment]
I see, it loads the tweets but it does not sort them chronologically. They are sorted by user. I will take a look on how to fix it.
