### ISSUE TITLE
Spelling mistake in Subscibe/Unsubscribe buttons

### ISSUE THREAD

**Issue by obeho** [pluja/Parasitter#190]
**Describe the bug**
Spelling mistake in Subscibe/Unsubscribe buttons in youtube channels on Yotter.

**To Reproduce**
1. Open any youtube channel in Yotter 
2. There's a red button that says _Unsuscribe_ or _Suscribe_ .

**Expected behavior**
The spelling has to be corrected to Subscibe/Unsubscribe.

**Screenshots**

![sss](https://user-images.githubusercontent.com/71698631/107148360-ae86e480-6978-11eb-9940-8f372a935735.png)
![ssss](https://user-images.githubusercontent.com/71698631/107148387-c78f9580-6978-11eb-9026-64975740a264.png)

**Additional context**
I'm on yotter.xyz server.

Btw, do you have any plans to provide subtites support?

**Comment by pluja** [comment]
Fixed, thank you for reporting.

Subtitles support are on the roadmap, but I am currently facing a work overload from my day-to-day job. As soon as things come back to normal I will start developing new features for Yotter again.

In the meantime, and as always, anyone can contribute and send a PR with any feature/fix and it will be very welcome!

**Comment by obeho** [comment]
@pluja btw, bookmarking/saving videos in youtube feature is missing, even though already implemented in Twitter.

**Comment by pluja** [comment]
@obeho  True, I will put extra effort on implementing new features closer to June as I will have much more time. I am currently studying a degree and working and my time is very limited. I have a lot of things in mind to implement in Yotter, but I don't have the time at the moment.

As always, everyone is welcome to make any PR in the meantime!

**Comment by FireMasterK** [comment]
What happened to your matrix account? You haven't been online in months 🤔

We should catch up sometime!

**Comment by pluja** [comment]
Oh, true. I have not been able to use Matrix. I will try to set it all up again later today!

**Comment by obeho** [comment]
> I am currently studying a degree and working and my time is very limited.

Completely understand. Thanks. Only when you can.
