### ISSUE TITLE
Error: Error decrypting url signatures: Could not find var_body

### ISSUE THREAD

**Issue by arankaren** [pluja/Parasitter#193]

**Comment by pluja** [comment]
Could you give a bit more context on this error?

**Comment by FireMasterK** [comment]
This is an error caused by cipher-protected URLs in YouTube, likely caused by an outdated youtube-dl version, it can be fixed by updating it.

Looks like `yt-dlc` is now no longer maintained.

**Comment by pluja** [comment]
Should we go back to `youtube-dl`?

**Comment by FireMasterK** [comment]
Yep, seems like the only good option for now.

**Comment by pluja** [comment]
Ok. Can you remind me why whe switched to `yt-dlc`? I can't remember why was it

**Comment by FireMasterK** [comment]
I believe it was because of faster updates because it was a community-maintained repository.

The maintainers of `youtube-dl` are slow and take forever to fix any breaking changes, they take a long time to review PRs, and didn't want to give more people write access.

You could see more about it at https://github.com/ytdl-org/youtube-dl/issues/26462

**Comment by pluja** [comment]
Okay! Thank you. I will check it and change it back to ytdl.

**Comment by pluja** [comment]
@FireMasterK I just found this: https://github.com/yt-dlp/yt-dlp

**Comment by FireMasterK** [comment]
I heard about it on the Invidious room too, it seems like a good idea to me

**Comment by user234683** [comment]
This was fixed [in this commit](https://github.com/user234683/youtube-local/commit/d998fea9b970406b50ee22b1998a52a96bbd1a29). They changed the base.js a little bit. You should be able to take the diff and apply it to watch_extraction.py.

**Comment by pluja** [comment]
Closing this as it should be solved. If anyone experiments this error again, we will reopen.
