### ISSUE TITLE
Add autofocus to search input fields

### ISSUE THREAD

**Issue by ghost** [pluja/Parasitter#194]
The search pages are exclusively used to search for something. I think it is a good idea to autofocus the search field, that I can start typing directly without the need to focus the input field.

My solution would look something like this _(not tested)_:

[app/templates/search.html](https://github.com/ytorg/Yotter/blob/dev-indep/app/templates/search.html#L9)
````python
{{ form.username(size=32, autofocus=true) }}<br>
````

[app/templates/ytsearch.html](https://github.com/ytorg/Yotter/blob/dev-indep/app/templates/ytsearch.html#L7)
````html
<input class="prompt" name="q" type="text" placeholder="Search..." autofocus>
````

**Comment by pluja** [comment]
Nice, I will add this!

**Comment by pluja** [comment]
Done, you can try it on yotter.xyz!

**Comment by ghost** [comment]
Awesome, thank you, works as expected!
