### ISSUE TITLE
I can’t subscribe to channels 

### ISSUE THREAD

**Issue by RouterCFW** [pluja/Parasitter#197]
I can’t subscribe to any channels on yotter

I’m on iOS 14.5 
Using safari 
I’ve tried to disable adblockers and other stuff but it still doesn’t work

**Comment by pluja** [comment]
I'll dig into this on Sunday. Thank you for reporting.

**Comment by pluja** [comment]
I made a small update. It should be working now. Can you confirm? I tried on my instance and I suscribed successfully

**Comment by LivingWithHippos** [comment]
I had to rebuild the docker image from the Dockerfile but now I can confirm that it works.

Sidenote: a breaking change in the cryptography python package forced me to update the Dockerfile adding `cargo rust`  to the apk install directive. See [here](https://github.com/pyca/cryptography/issues/5771) for details and alternative options (and also lots of anger lol). I can open a PR if needed.

**Comment by FireMasterK** [comment]
Looks like the `cryptography` package will need rust in the future, something needs to be done for `pypy` Dockerfile as well, as installing rust isn't straightforward there.

**Comment by RouterCFW** [comment]
It’s fixed now thanks :)
