### ISSUE TITLE
Add volume information for Docker

### ISSUE THREAD

**Issue by arnaubennassar** [pluja/Parasitter#26]
I'm trying to use Yotter with Docker, but there is no volume information (at least on the README). Therefore persistence can't be achieved.

Could you update the README to include this?

**Comment by pluja** [comment]
Hi! Feel free to make a PR with the solution to this. I don't really ever use Docker and I don't know ho to address this issue. If you don't know too, maybe @Sn0wed1 or @SuperSandro2000 can help you with this.

**Comment by arnaubennassar** [comment]
I've looked into it, and apparently, the only file needed to persist is `app.db`, right?

I don't mind adding the Docker stuff but I would prefer not to touch the rest of the code, and there's one thing that may be problematic: `app.db` is stored on the same directory of the code. Because of that, it's not possible to provide a volume to persist the file, since when the path of the volume is set it overwrites what was there: the code to run the app.

Is there a way to configure where the DB file is stored?

**Comment by pluja** [comment]
File `app.db`, which contains the Database with all the user data, and folder `migrations/`, which contains the database migrations for future updates, should persist.

I will try to look into it and find a way to store anything related to the Database on a custom path.

**Comment by arnaubennassar** [comment]
A part from that, I've seen that @Sn0wed1 has forked the repo and apparently is the one uploading the images to Docker Hub.
Could you explain how this flow works?
If you want I could add a GitHub action so every time there's a new commit to master, the Docker Hub image is built and published. You only would need to add a GitHub secret with a Docker Hub user and pass (only the admin of the repo can do this).

**Comment by pluja** [comment]
Yes. Since I'm not familiar with Docker, he is somewhat maintaining Docker-related things in a non-officially entitled way.

**Comment by pluja** [comment]
I am opening a Matrix room to discuss these things. Feel free to enter there, and we can talk in a more fluid way. Check [#Contributing](https://github.com/pluja/Yotter#contributing).

**Comment by SuperSandro2000** [comment]
What is the full path of the database? If it does not have its own directory Docker can't persist it.

The line we need to add is the following but with the correct path: ``VOLUME /path/to/app.db``.

Why is migrations not in the source code?

**Comment by arnaubennassar** [comment]
> What is the full path of the database? If it does not have its own directory Docker can't persist it.

Inside Docker, the path is `/usr/src/app/app.db`, same path were the code is (`/usr/src/app/`)

> Why is migrations not in the source code?

I guess that they are on the code. Haven't found where, probably to my lack of knowledge of the framework. 

But, if they're not in the code where are they? I've been able to use the app with Docker with the db working and without using volumes, so it has to be somewhere in the code, and therefore there is no need to do anything extra on that side

**Comment by pluja** [comment]
The migrations folder is generated when runing `flask db migrate` using Flask-Migrate. This extension is a Flask wrapper for Alembic, a database migration framework for SQLAlchemy. This allows making updates to an existing database as the application needs change or grow. Relational databases are centered around structured data, so when the structure changes the data that is already in the database it needs to be migrated to the modified structure.

**Comment by FireMasterK** [comment]
Closing this as the docker-compose file achieves this.
