### ISSUE TITLE
Improve proxy-streaming videos through Yotter

### ISSUE THREAD

**Issue by pluja** [pluja/Parasitter#27]
Currently, it works OK, but I am sure it can be improved a LOT more.

If you play a large video (say 50min or more) you can see that when trying to go a moderately large amount of minutes forward (i.e 25min) it takes a looong time.

I will be investigating on this, but if anyone knows something it would be very good to get some help.

**Comment by user234683** [comment]
I believe you need to include the `Range` header from the client when forwarding the request, since the browser video player makes a new HTTP range request when jumping forward in the video. It's probably also a good idea to include the `Content-Range` header in the response. And you'll want to make sure you include the same http status code returned by googlevideo, so that the range requests get the 206 Partial Content codes back that they need. You can see this in action if you play a video in the browser with the network tab in devtools open

**Comment by pluja** [comment]
Woah, awesome thanks. I'm a newbie with this kind of things and I'm learning!

I was told that it would be better to use Nginx for the proxy-streaming of videos, so I will give it a try.

**Comment by FireMasterK** [comment]
Another thing I noticed that there is no keep-alive, this is useful when serving a lot of requests to a particular client.

**Comment by pluja** [comment]
@FireMasterK  If you want to add it and make a PR along with the docker, this is handled on `app/routes.py` on the `@app.route('/stream<url>')>`.

If you can't I will do it when I can.

**Comment by pluja** [comment]
@FireMasterK @user234683 Do you think it would be better to handle this from Nginx rather than with the Python server? I was told Python is slow.

**Comment by FireMasterK** [comment]
Yes, absolutely, that's one of my major concerns with other projects such as invidious, the video proxy was extremely slow compared to an implementation with Nginx, I feel we should still have a fallback in the app tho for those who don't use Nginx.

**Comment by pluja** [comment]
Nice. Do you know how this would be implemented? I am looking into ways to do so but can't find anything. I've worked very little with Nginx and I don't know how this should be addressed.

PS. You can join our Matrix room if you think it would be better to chat

**Comment by FireMasterK** [comment]
Yes, I think I do, I joined the matrix room. I'll take a look at it after I finish the docker stuff

**Comment by pluja** [comment]
Awesome!

**Comment by FireMasterK** [comment]
```
        location /videoplayback {
                proxy_buffering off;
                resolver 1.1.1.1;
                proxy_pass https://$arg_hostname;
                proxy_set_header Host $arg_hostname;
                add_header Access-Control-Allow-Origin *;
        }
```

**Comment by FireMasterK** [comment]
All you'll have to do is just change the hostname to from the googlevideo one to the instance's one and just append the target hostname in a query parameter, similar to how invidious does it.

**Comment by pluja** [comment]
So If I want to use this videoId: NKaA0IPcD_Q and this URL:
```
https://r4---sn-4g5e6ns6.googlevideo.com/videoplayback?expire=1599743176&ei=aNBZX-CTK93ZxN8PuJezkAE&ip=92.185.139.170&id=o-AAUQfcvT5vz0-cezbMe1Lln6bY7_GmYL15Rg7lc9Pl8b&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&vprv=1&mime=video%2Fmp4&gir=yes&clen=42593939&dur=157.160&lmt=1389956063621479&fvip=4&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIga9o3CWB1Hib7y6nYFN4-ByNILzaI4bUXwIuZQyiowvACIQDXTUGOAOd75Y8IyyEB6oE6e00mejZMVnOEMSUhjJhyTw%3D%3D&ratebypass=yes&cm2rm=sn-vg5obxn25po-cjo67r,sn-h5qse7z&req_id=b0e5d3473f07a3ee&ipbypass=yes&redirect_counter=2&cms_redirect=yes&mh=Km&mm=34&mn=sn-4g5e6ns6&ms=ltu&mt=1599721463&mv=m&mvi=4&pl=20&lsparams=ipbypass,mh,mm,mn,ms,mv,mvi,pl&lsig=AG3C_xAwRAIgCLecD6M38Pbp_SQLvmhZ7Jj092gsU-gSzUQFvPBwlgICIC-ZwIaB59UC29GX_HhB7L6Nenc-egY5yq4SY2bwq7A6
```

Once the `/videoplayback` is set up on Nginx, should i do it like this?
```
https://yotter.xyz/videoplayback?expire=1599743176&ei=aNBZX-CTK93ZxN8PuJezkAE&ip=92.185.139.170&id=o-AAUQfcvT5vz0-cezbMe1Lln6bY7_GmYL15Rg7lc9Pl8b&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&vprv=1&mime=video%2Fmp4&gir=yes&clen=42593939&dur=157.160&lmt=1389956063621479&fvip=4&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIga9o3CWB1Hib7y6nYFN4-ByNILzaI4bUXwIuZQyiowvACIQDXTUGOAOd75Y8IyyEB6oE6e00mejZMVnOEMSUhjJhyTw%3D%3D&ratebypass=yes&cm2rm=sn-vg5obxn25po-cjo67r,sn-h5qse7z&req_id=b0e5d3473f07a3ee&ipbypass=yes&redirect_counter=2&cms_redirect=yes&mh=Km&mm=34&mn=sn-4g5e6ns6&ms=ltu&mt=1599721463&mv=m&mvi=4&pl=20&lsparams=ipbypass,mh,mm,mn,ms,mv,mvi,pl&lsig=AG3C_xAwRAIgCLecD6M38Pbp_SQLvmhZ7Jj092gsU-gSzUQFvPBwlgICIC-ZwIaB59UC29GX_HhB7L6Nenc-egY5yq4SY2bwq7A6
```

And then provide a query parameter whith the hostname that would be: `r4---sn-4g5e6ns6.googlevideo.com`

**Comment by pluja** [comment]
I added support for Nginx streaming on this commit: d01e418c2f254fb73bda52c0792067a213ab035e

I added a variable on `yotter-config.json` so you can choose to use Python streaming or Nginx streaming.

**Comment by pluja** [comment]
I hate I always forget to mentinon issues on the commit comment.

Added instructions on the documentation: 36f24e4832188ed766ba19c62045e2169281a400

**Comment by FireMasterK** [comment]
Can we do something similar for thumbnails/images too?

**Comment by pluja** [comment]
Same technique should work? I think something can be done for sure.

**Comment by FireMasterK** [comment]
Indeed, I made an slight alteration in the config for it.
Example URL: Click [here](https://yotter.kavin.rocks/vi/mayvv2asTps/hqdefault.jpg?sqp=-oaymwEiCMQBEG5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLA-6TYYklFN_1xy0pxclDH9iaGHZw&hostname=i.ytimg.com)
All it requires is just changing the location part of it to `location ~ (/videoplayback|/vi/)`

**Comment by FireMasterK** [comment]
I can confirm, the streaming of videos works perfectly.

**Comment by pluja** [comment]
So we can close this issue now.

**Comment by pluja** [comment]
Thank you @FireMasterK
