### ISSUE TITLE
Instance requirements

### ISSUE THREAD

**Issue by FireMasterK** [pluja/Parasitter#30]
Hi there,

I'm looking for a minimum requirements for running an instance of Yotter on Docker, how much ram and cpu cores are required?

Thanks

**Comment by pluja** [comment]
If you want for personal use, Docker is fine. But if you want to host an instance and offer the service to more than one user at the same time, you can't use the flask server (the one being used with Docker installation).

Instead, you should follow [this instructions](https://github.com/pluja/Yotter/blob/dev-indep/SELF-HOSTING.md) which are the guidelines for setting up a public instance on a production-ready server.

My instance, https://yotter.xyz/, is hosting now 16 users and works pretty fine. The VPS I have right now is 2GB of RAM.

**Comment by FireMasterK** [comment]
Got it, thanks! Is there any way to automatically keep it up to date?

**Comment by pluja** [comment]
There isn't a way to do it directly. But sure you can write a script with the necessary commands to update the instance and make it run once a week / month with a cronjob.

**Comment by pluja** [comment]
I'm closing this issue, if you have further questions we can still talk here or you can join our Matrix room.
