### ISSUE TITLE
Set up Continuous integration

### ISSUE THREAD

**Issue by mauriciabad** [pluja/Parasitter#59]
Set up a CI pipeline to run tests and build the application. 
This ensures that pull requests don't merge code with errors. 

For now, I suggest just setting up [Travis CI](https://travis-ci.org/) to run the build command. Tests can be added latter.

**Comment by FireMasterK** [comment]
@pluja would you like me to do this?

**Comment by pluja** [comment]
Yes, if you can it would be great!

**Comment by FireMasterK** [comment]
Closed with 1242b49f8d08f981772937bc487da43fe44e4345, currently no tests are setup tho.
