### ISSUE TITLE
Youtube: Break dependence wiht Invidious

### ISSUE THREAD

**Issue by pluja** [pluja/Parasitter#7]
As Invidious is closing the main instance and development will significantlly slow down, I want to break the dependence with it. You can read more about this [here](https://github.com/iv-org/invidious/issues/1320).

I don't really know how I will be doing this so any ideas or help is really welcome :D

TODO:
- [x] Proxy videos through Parasitter server for improved privacy.
- [x] Get thumbnails through Parasitter (proxy)

**Comment by pluja** [comment]
Currently you can already change the Invidious and Nitter instance with ease (on the code), but breaking any kind of dependence would be good.

I will be implementing an option on the settings page to change the instances more easily. Anything related to "first version" of settings page must go on #5

**Comment by JotaPe** [comment]
Instead of using Invidious or Nitter you can use [RSS-Bridge](https://github.com/RSS-Bridge/rss-bridge), it has support for a bunch of social media.

If you don't like the idea, at least you can see how RSS-Bridge generate RSS.

**Comment by pluja** [comment]
@JotaPe Thanks! I'll take a look at it!

**Comment by pluja** [comment]
[New branch](https://github.com/pluja/Parasitter/tree/dev-indep) created. It will break all dependence with Invidious and Nitter.

**Comment by pluja** [comment]
Using this URL we can get a feed from Youtube directly, without Invidious.

https://www.youtube.com/feeds/videos.xml?channel_id=<channel_id>

**Comment by user234683** [comment]
I have a [mini-module](https://github.com/user234683/youtube-local/tree/master/youtube/yt_data_extract) written in Python for parsing data from the Youtube polymer API that you can reference or adapt. It's not documented, has rough edges, and might change a lot though. Let me know if you need any help with request/parsing tasks.

**Comment by pluja** [comment]
@user234683 I'll take a look, thanks!!

**Comment by pluja** [comment]
Solved in: 6865455e7c743241dfc06847a8f9cea036f215b6
