### ISSUE TITLE
Adding Importing data from Invidious

### ISSUE THREAD

**Issue by ghost** [pluja/Parasitter#79]
Migrating from Invidious and so far I either get a 500 error, or if it does go through it hangs on a blank page and after that imports only 5 subscriptions from the file, out of several. I've tested with all three of Invidious' options, so exported from OPLM and it's Newpipe equivalent, as well as .json, I'm certain it's formatted the way it should though I'm thinking it might not support Invidious, not sure on that one.

Tested with the yotter.jank.media instance.

**Comment by FireMasterK** [comment]
I can confirm this happens with newpipe too

**Comment by pluja** [comment]
I didn't implement the feature myself, @0ihgk1uVBLlTBzVo7F9B was who did it. I will take a look on it if he can't do it!

**Comment by 0ihgk1uVBLlTBzVo7F9B** [comment]
I will take a look.

**Comment by pluja** [comment]
@0ihgk1uVBLlTBzVo7F9B Can we consider this as solved?

**Comment by FireMasterK** [comment]
I can confirm, the issue has been fixed, however, I get a gateway timeout on my instance (with 70 subscriptions), could we make the import process asynchronous or run it as a task?

**Comment by pluja** [comment]
This would be ideal, it should be a background process. We can look up on how to improve this. I will close this issue and open a new one with more specific detail.
