### ISSUE TITLE
Images not being proxied

### ISSUE THREAD

**Issue by FireMasterK** [pluja/Parasitter#81]
Example URL: https://yotter.kavin.rocks/c/UCYEK6xds6eo-3tr4xRdflmQ

**Comment by FireMasterK** [comment]
The same is true when searching for something too.

**Comment by pluja** [comment]
Latest commit (1c02914b90ab1b2ded73fd53d38b9d3faf3d0091) should solve this. You need to add `/a` to the nginx file.

```
    location ~ (/videoplayback|/vi/|/a) {
           . . .
    }
```

**Comment by FireMasterK** [comment]
Can confirm that this is fixed in the /c/ route, but this is not fixed when searching for videos, it still connects to youtube.

Also, any reason why you used `/a` and `/a/` in the Nginx config? That would also match the username on `/a` which is unnecessary afaik.

**Comment by pluja** [comment]
I just didn't thought about it, whe I tested it I've seen it is wrong! I'll be fixing this for the youtube search too.
