### ISSUE TITLE
Videos pause after 5-6 mins and dont recover.

### ISSUE THREAD

**Issue by jankytech** [pluja/Parasitter#82]
Hey I am the owner of yotter.jank.media and have noticed that the video feed on my server stops after 5-6 mins regardless of the video. I am running in docker and using caddy2 as a webserver if that helps. Has anyone else experienced this issue? I havent experienced the same issue on yotter.kavin.rocks

Any ideas?

**Comment by jankytech** [comment]
Here are the logs for me skipping through until it freezes. Nothing of note that I can see:

```--- 14.250005722045898 seconds fetching youtube feed---
--- 0.0010704994201660156 seconds fetching youtube feed---
[2020-09-26 00:40:37 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:815)
[2020-09-26 00:40:37 +0000] [815] [INFO] Worker exiting (pid: 815)
--- 0.2677593231201172 seconds fetching youtube feed---
[2020-09-26 00:40:37 +0000] [819] [INFO] Booting worker with pid: 819

**Comment by pluja** [comment]
Are you proxying through Nginx? Or are you using the default wich is using the Python flask server itself?

**Comment by FireMasterK** [comment]
I believe that instance uses flask considering that there are timeouts in the logs.

This is caused by videojs using a `Range` header such as `1234-` which would request for all data after 1234 bytes which would keep a connection open until the entire video is downloaded which would explain why this happens.

Could we somehow [stream the content through flask](https://flask.palletsprojects.com/en/1.1.x/patterns/streaming/)? I found a [simple example](https://gist.github.com/fanzeyi/7490019) snippet which claims to be able to do so.
We should also consider [retying on network errors](https://github.com/videojs/video.js/issues/1805#issuecomment-273671931) similar to how invidious does.

**Comment by jankytech** [comment]
I am proxying through caddy2 which is the proxy for other services on the system and not nginx (so I guess its the flask server under the hood). Would using nginx fix the issue?

**Comment by pluja** [comment]
The nginx proxy is much more efficient and also can handle much more requests and loads. So using the nginx proxy for the video is highly recommended for instances with more than one user. You can checkout the info about how to do it here:
https://github.com/ytorg/Yotter/blob/dev-indep/SELF-HOSTING.md#nginx-set-up-and-HTTPS

**Comment by FireMasterK** [comment]
Yes, ideally you use your reverse proxy for this as python is quite inefficient for serving large files.

This is the location you should add if you use Nginx.
```
location ~ (/videoplayback|/vi/|/a/) {
       proxy_buffering off;
       resolver 1.1.1.1;
       proxy_pass https://$arg_host;
       proxy_set_header Host $arg_host;
       add_header Access-Control-Allow-Origin *;
}
```

If you prefer using caddy instead of Nginx and know how to translate this to caddy, you can do that too.

**Comment by pluja** [comment]
@FireMasterK note that `$arg_hostname` should be `$arg_host`

**Comment by FireMasterK** [comment]
You're right, I forgot about that :P

**Comment by jankytech** [comment]
Wonderful thanks guys. Will try this out.

**Comment by jankytech** [comment]
Nice one. It seems to be working now. I was having issues for a while but needed to do a pull from the repo to fix the hostname->host query parameter change and probably a load of other changes. The nginx config worked once that was pulled though. Thanks for your help!

**Comment by obeho** [comment]
@pluja I'm getting SSL_PROTOCOL_ERROR for this instance (something about invalid certificate). Perhaps it should be removed from [here](https://github.com/ytorg/Yotter#public-instances), after due consideration?
