### ISSUE TITLE
Are passwords hashed with salt?

### ISSUE THREAD

**Issue by nbe1233** [pluja/Parasitter#84]
In README.md
> The only things the database stores are:
> Hash of the password

It does not mention whether the passwords are salted or not.

**Comment by FireMasterK** [comment]
I can confirm they are salted with a salt length of 8
https://techmonger.github.io/4/secure-passwords-werkzeug/
Check out generate_password_hash in that link

**Comment by pluja** [comment]
As @FireMasterK stated, they are. The password library we are using Werkezeug salts the passwords by default.
