### ISSUE TITLE
Getting "Error: Target database is not up to date." when running with Docker

### ISSUE THREAD

**Issue by Nico769** [pluja/Parasitter#87]
Running Yotter with Docker using `docker-compose up` causes its container to exit with the following error ([see here](https://pastebin.com/cy03xKsQ) for the full logs dump):
```
yotter_1   | ERROR [root] Error: Target database is not up to date.
```
After [reading this](https://stackoverflow.com/questions/17768940/target-database-is-not-up-to-date) I modified the `Dockerfile` as follows:
```
[..]
COPY . .

RUN flask db init \
  && flask db migrate \
  && flask db upgrade

CMD flask db stamp head \ # Added this line
  && flask db migrate \
  && flask db upgrade \
  && gunicorn -b 0.0.0.0:5000 -w 4 yotter:app

EXPOSE 5000
```
Rebuilding the image and pointing `docker-compose.yml` to the latest image resolved the issue, as you can see in this [logs dump](https://pastebin.com/0jPhHbLe).

If that is ok with you, I'd be happy to make a PR solving this and removing the duplicated `ports` option under `yotter` service in the `docker-compose.yml` :).

**Comment by FireMasterK** [comment]
Interesting, can you confirm that there's no data lost when doing so? Feel free to create a PR :)

**Comment by Nico769** [comment]
Could you give me some pointers on how I should effectively test that? I've never used Flask nor the ecosystem of libraries around it 😅.

**Comment by FireMasterK** [comment]
A simple way to do that could maybe start Yotter, do something that changes something in the database such as subscribing to a channel and then restart Yotter to see if the changes stick around.

**Comment by Nico769** [comment]
Oh ok, I was on the right track then but I asked anyway, just to be safe :).

I've done the following:

1. Ran Yotter with `docker-compose up -d` and created a test account;
2. Saved a Twitter post and followed my Twitter handle;
3. Logged out and ran `docker-compose down`;
4. Ensured that all the containers were correctly removed with `docker-compose ps -a`;
5. Ran Yotter again and ensured that all my changes were still there (they were).

What do you think?

**Comment by FireMasterK** [comment]
Awesome! That's perfect, feel free to make a PR :)

**Comment by Nico769** [comment]
Thanks, I'm closing this :).
