### ISSUE TITLE
Sharing videos with friends/family

### ISSUE THREAD

**Issue by Duckbilled** [pluja/Parasitter#94]
I really like using yotter and massive thanks for the hard work. It would be nice to be able to have a front end like invidious which doesn't require an account so it is easier to share videos with others. I understand that it is better for load balancing on small server, but will this be solved in the future?

**Comment by FireMasterK** [comment]
See #29, I think what you're looking for is a way to make your instance public, just like in Invidious?

**Comment by Duckbilled** [comment]
Yes, sorry I didn't read the description well enough before.
