### ISSUE TITLE
Make the import process run on background

### ISSUE THREAD

**Issue by pluja** [pluja/Parasitter#95]
The account import process now takes place on the same server session. Ideally it should run on the background as a task or in an asynchronous mode for a better user experience.

**Comment by Christiankoo** [comment]
Can i take this issue, please?

**Comment by FireMasterK** [comment]
Sure, feel free to 👍, as far as I'm aware, I don't think anyone else is working on this issue

**Comment by pluja** [comment]
Yes! You can @Christiankoo

**Comment by pluja** [comment]
Solved by @Christiankoo in b5a0f84
